[build]
  command = "npm run build && node copy-netlify-files.js"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000

# This is the most important part for fixing SPA routing in Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# API forwarding to serverless functions if needed
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure proper caching for static assets but no caching for HTML
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
  NODE_VERSION = "18"