[build]
  command = "npm run build && node netlify.js"
  publish = "dist"

# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev" # Command to start your dev server
  port = 3000 # Port that the dev server will be accessible on
  publish = "dist" # If you use a _redirect file, provide the path to your static content folder