# netlify.toml
# This file tells Netlify how to build and deploy your site

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# This redirect rule is the key fix for SPA routing in Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"